### ISSUE TITLE
Getting NPE while running shadow Jar from a new laambda

### ISSUE THREAD

**Issue by vibskant007** [blackboard/lambda-selenium#28]
Created new Lambda and uploaded jar through s3 link and invoked  lambda using API Gateway:
StackTrace:
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:264)
at com.blackboard.testing.lambda.LambdaTestHandler.getTestClass(LambdaTestHandler.java:59)
at com.blackboard.testing.lambda.LambdaTestHandler.handleRequest(LambdaTestHandler.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at lambdainternal.EventHandlerLoader$PojoMethodRequestHandler.handleRequest(EventHandlerLoader.java:259)
at lambdainternal.EventHandlerLoader$PojoHandlerAsStreamHandler.handleRequest(EventHandlerLoader.java:178)
at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:888)
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:283)
at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:64)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:94)

**Comment by wesmcouch** [comment]
Hello, I would pull latest master and try the new auto-deployment method. You may need to delete resources in your AWS account to allow for the auto-deployment to be successful. Check the CloudFormation output when deploying to verify. 

Follow the instructions here https://blackboard.github.io/lambda-selenium/java-tutorial.html
