### ISSUE TITLE
java.lang.Throwable: The driver is not executable: /var/task/lib/chromedriver

### ISSUE THREAD

**Issue by ashwiniananthaswamy** [blackboard/lambda-selenium#35]
Hi,

   I cloned the project locally and I tried the below steps:

1. Installed serverless on my **windows 10** machine
2, CD into **lambda-selenium-java**
2. Ran command: `gradle clean unzipLibs shadowJar`
    Note: I did not use gradle task deploy in the above command since it wasn't working on windows.
3. Deployed the code to AWS using the below serverless command:
    `serverless deploy --force`
4. I was successfully able to deploy the code to AWS and I was able to verify that the lambda function, S3 bucket and the cloudWatch logs were created
5. I run the tests I get the following error:
   ```
 java.lang.IllegalStateException: The driver is not executable: /var/task/lib/chromedriver
at com.google.common.base.Preconditions.checkState(Preconditions.java:534)
at org.openqa.selenium.remote.service.DriverService.checkExecutable(DriverService.java:140)
at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:131)
at org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:32)
at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:
```

Note: I downloaded the latest release(Alpha 0.13) from the project, uploaded to S3 and pointed Lambda to the uploaded release version after which I am able to successfully run the tests. Not sure what is different from the release version on github and locally building and deploying the jar files using serverless.

Thank you for your help.

**Comment by wesmcouch** [comment]
Hello, the package in the release isn't quite synced up to master and the latest tutorial. The instructions on https://blackboard.github.io/lambda-selenium/java-tutorial.html don't require the release, if you just run those commands it should get you up and running.

**Comment by BanjoFromCurlwaa** [comment]
Hi
I am also getting this error.  When I try to follow the instructions exactly (ie cloning directly using git), I get the error 

Cloning into 'lambda-selenium'...
The authenticity of host 'github.com (192.30.255.113)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? Y
Please type 'yes' or 'no': yes
Warning: Permanently added 'github.com,192.30.255.113' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by wesmcouch** [comment]
@BanjoFromCurlwaa, this wasn't designed to ever run on windows, you can checkout my comments here regarding windows setup that worked for someone else https://github.com/blackboard/lambda-selenium/issues/32

**Comment by BanjoFromCurlwaa** [comment]
Hi thanks, I will move to following the instructions in Ubuntu once the IT team have created an environment for me.

**Comment by BanjoFromCurlwaa** [comment]
Hi, could the error:
java.lang.RuntimeException: java.lang.Throwable: The driver is not executable: /var/task/lib/chromedriver
be related to my not having set up internet access on my aws account?  (given that it failed when I ran through the docker instructions provided in thread #32 with the same error)

**Comment by ramonview** [comment]
Hello, looks like this issue is still open, I am getting "The driver is not executable: /var/task/lib/chromedriver" exactly same as above.   I have tried this from both Windows and mac...no luck. Any solution available ? Please help me, overall this framework shows promising, want to get the solution for this chromedriver issue.

**Comment by sashagam** [comment]
Hi!
Faced same issue with The driver is not executable: /var/task/lib/chromedriver
Found the root cause in windows zip/unzip. In my case when I unzip and zip on windows the permissions on chromedriver where empty. But if you unzip and zip on linux permissions remained alright.

**Comment by tsu-denim** [comment]
https://github.com/blackboard/lambda-selenium/issues/19

In regards to zipping ^. Sorry, have been out of the Selenium biz, but
still can't believe nobody is integrating Lambda/Selenium in a better way.
Will try to find some time to support this more.

**Comment by mrajendrac** [comment]
This issue is about permissions set to chromedriver during shadowJar gradle task, I am still searching for a solution.

Thanks,
Rajendra

**Comment by anirseven** [comment]
Hi, I am facing the same issue, was trying to recreate running the Selenium Tests on AWS Lambda and followed the instruction as in https://aws.amazon.com/blogs/devops/ui-testing-at-scale-with-aws-lambda/

One doubt on the above documentation is I am unable to find libgconf-2.so.4 and libORBit-2.so.0 from the AWS Linux AMI in order to place them in the java/resources/lib folder of the project.

Can you let know what has changed since the article was published? @wesmcouch 


Getting below error 
{
  "errorMessage": "The driver is not executable: /var/task/lib/chromedriver",
  "errorType": "java.lang.IllegalStateException",
