### ISSUE TITLE
"errorMessage": "Server terminated early with status 127",

### ISSUE THREAD

**Issue by aravindsridharamoorthy** [blackboard/lambda-selenium#51]
Hi,

I am getting error message "errorMessage": "Server terminated early with status 127" when I did the same thing as mentioned in the video.

Not sure where I am going wrong. Can you please help me.

**Comment by rprusia** [comment]
I have the same issue.  Can someone provide us with some guidance on how to fix issue?

**Comment by rprusia** [comment]
I was able to resolve my issue by using node js 8 instead of node js 10 in the lambda function.

**Comment by rsshilli** [comment]
I had this problem because I couldn't run chromedriver from the command line.  When I ran it, it was missing a library.  I fixed that (and making sure chrome could run) and then it worked.

**Comment by actioncorp3** [comment]
> I was able to resolve my issue by using node js 8 instead of node js 10 in the lambda function.

Hello rprusia, how did you change a node js 8? From the console it only allows me to switch to node js 10 and 12. Can you please help me pliz.

**Comment by rsshilli** [comment]
@actioncorp3 Unfortunately Node 8 has been discontinued by AWS. We now use https://www.npmjs.com/package/puppeteer-core

**Comment by Junaid1111** [comment]
{
  "errorType": "Error",
  "errorMessage": "Server terminated early with status 127",
  "trace": [
    "Error: Server terminated early with status 127",
    "    at /var/task/node_modules/selenium-webdriver/remote/index.js:252:52",
    "    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
    "From: Task: WebDriver.createSession()",
    "    at Function.createSession (/var/task/node_modules/selenium-webdriver/lib/webdriver.js:777:24)",
    "    at Function.createSession (/var/task/node_modules/selenium-webdriver/chrome.js:719:29)",
    "    at createDriver (/var/task/node_modules/selenium-webdriver/index.js:167:33)",
    "    at Builder.build (/var/task/node_modules/selenium-webdriver/index.js:639:16)",
    "    at Runtime.exports.handler (/var/task/index.js:29:26)",
    "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
  ]
}

Getting This Error Running Nodejs LambdaSelenium using Node 12.x and 10.x...!

Any Suggestions to Resolve this issue??

**Comment by Junaid1111** [comment]
> @actioncorp3 Unfortunately Node 8 has been discontinued by AWS. We now use https://www.npmjs.com/package/puppeteer-core


How can i use this with LambdaSelenium ??

**Comment by deep9699** [comment]
I have same issue like https://github.com/blackboard/lambda-selenium/issues/51#issuecomment-613755287 any solution for the same ?
